depth.0: 16
embed_channels.0: 576
mlp_ratio.0: 3.5
mlp_ratio.1: 3
mlp_ratio.10: 4
mlp_ratio.11: 3.5
mlp_ratio.12: 4
mlp_ratio.13: 3
mlp_ratio.14: 3.5
mlp_ratio.15: 3
mlp_ratio.2: 3
mlp_ratio.3: 3
mlp_ratio.4: 3
mlp_ratio.5: 3
mlp_ratio.6: 3
mlp_ratio.7: 3
mlp_ratio.8: 3
mlp_ratio.9: 3.5
num_heads.0: 9
num_heads.1: 10
num_heads.10: 10
num_heads.11: 9
num_heads.12: 9
num_heads.13: 9
num_heads.14: 9
num_heads.15: 9
num_heads.2: 9
num_heads.3: 9
num_heads.4: 9
num_heads.5: 9
num_heads.6: 9
num_heads.7: 10
num_heads.8: 9
num_heads.9: 10
