depth.0: 14
embed_channels.0: 384
mlp_ratio.0: 4
mlp_ratio.1: 4
mlp_ratio.10: 4
mlp_ratio.11: 4
mlp_ratio.12: 4
mlp_ratio.13: 3.5
mlp_ratio.2: 4
mlp_ratio.3: 3
mlp_ratio.4: 3.5
mlp_ratio.5: 3.5
mlp_ratio.6: 4
mlp_ratio.7: 3.5
mlp_ratio.8: 3.5
mlp_ratio.9: 3.5
num_heads.0: 5
num_heads.1: 5
num_heads.10: 7
num_heads.11: 5
num_heads.12: 6
num_heads.13: 6
num_heads.2: 5
num_heads.3: 5
num_heads.4: 5
num_heads.5: 7
num_heads.6: 6
num_heads.7: 6
num_heads.8: 5
num_heads.9: 7
