depth.0: 14
embed_channels.0: 216
mlp_ratio.0: 3
mlp_ratio.1: 3
mlp_ratio.10: 4
mlp_ratio.11: 4
mlp_ratio.12: 4
mlp_ratio.13: 4
mlp_ratio.2: 3
mlp_ratio.3: 3.5
mlp_ratio.4: 3.5
mlp_ratio.5: 3.5
mlp_ratio.6: 3
mlp_ratio.7: 4
mlp_ratio.8: 3
mlp_ratio.9: 4
num_heads.0: 3
num_heads.1: 3
num_heads.10: 4
num_heads.11: 4
num_heads.12: 4
num_heads.13: 4
num_heads.2: 3
num_heads.3: 3
num_heads.4: 3
num_heads.5: 3
num_heads.6: 4
num_heads.7: 3
num_heads.8: 3
num_heads.9: 3
